# Generated by Django 3.1.7 on 2021-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210722_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='task',
            field=models.TextField(blank=True),
        ),
    ]
